apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jcu-site
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: jcu-site
  path: ./deploy
  prune: true
  wait: true
  images:
    - name: ghcr.io/tonybutt/jcu-site
      newTag: "20260327045549" # {"$imagepolicy": "flux-system:jcu-site:tag"}
