apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gems-push
  namespace: flux-system
spec:
  interval: 10m
  url: ssh://git@github.com/tonybutt/gems
  ref:
    branch: main
  secretRef:
    name: gems-flux-push
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: jcu-site
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: gems-push
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: "chore(jcu-site): {{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}"
    push:
      branch: main
  update:
    path: ./apps/jcu-site
