apiVersion: v1
kind: ConfigMap
metadata:
  name: jcu-config
data:
  config.toml: |
    listen_addr = "0.0.0.0:8080"
    database_path = "/data/jcu.db"
    static_dir = "/usr/share/web"
    s3_bucket = "jcu-alumni-media-dev"
    s3_endpoint = "https://44100e4b0f3d2cbc656b2dc06a9be540.r2.cloudflarestorage.com"
    s3_region = "auto"
    resend_from = "noreply@jcu.abutt.dev"
    app_url = "https://jcu.abutt.dev"
