apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-hostpath
  namespace: openebs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: openebs.io/local
parameters:
  hostpath: /var/openebs/local
