---
# Source: oauth2-proxy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: oauth2-proxy    
    helm.sh/chart: oauth2-proxy-10.3.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: oauth2-proxy
    app.kubernetes.io/version: "7.15.0"
  name: oauth2-proxy
  namespace: oauth2-proxy
automountServiceAccountToken: true
---
# Source: oauth2-proxy/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: oauth2-proxy    
    helm.sh/chart: oauth2-proxy-10.3.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: oauth2-proxy
    app.kubernetes.io/version: "7.15.0"
  name: oauth2-proxy
  namespace: oauth2-proxy
type: Opaque
data:
  
  cookie-secret: "WFhYWFhYWFhYWFhYWFhYWA=="
  client-secret: "WFhYWFhYWFg="
  client-id: "WFhYWFhYWA=="
---
# Source: oauth2-proxy/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: oauth2-proxy    
    helm.sh/chart: oauth2-proxy-10.3.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: oauth2-proxy
    app.kubernetes.io/version: "7.15.0"
  name: oauth2-proxy
  namespace: oauth2-proxy
data:
  oauth2_proxy.cfg: "provider = \"oidc\"\noidc_issuer_url = \"https://sso.abutt.dev/oauth2/openid/oauth2-proxy\"\nemail_domains = [ \"*\" ]\nclient_id = \"oauth2-proxy\"\ncode_challenge_method = \"S256\"\nclient_secret_file = \"/run/secrets/client-secret\"\ncookie_secret_file = \"/run/secrets/cookie-secret\"\ncookie_secure = true\ncookie_samesite = \"lax\"\ncookie_httponly = true\ncookie_expire = \"168h\"\ncookie_refresh = \"1h\"\nreverse_proxy = true\nset_xauthrequest = true\nset_authorization_header = true\npass_access_token = true\npass_user_headers = true\nskip_auth_routes = [\n  \"^/health\",\n  \"^/ready\",\n  \"^/metrics\"\n]\nupstreams = [ \"http://valentines.valentines.svc.cluster.local:80\" ]\nwhitelist_domains = [ \".abutt.dev\" ]"
---
# Source: oauth2-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy    
    helm.sh/chart: oauth2-proxy-10.3.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: oauth2-proxy
    app.kubernetes.io/version: "7.15.0"
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      appProtocol: http
      name: http
    - port: 44180
      protocol: TCP
      appProtocol: http
      targetPort: metrics
      name: metrics
  selector:    
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: oauth2-proxy
---
# Source: oauth2-proxy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy    
    helm.sh/chart: oauth2-proxy-10.3.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: oauth2-proxy
    app.kubernetes.io/version: "7.15.0"
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:      
      app.kubernetes.io/name: oauth2-proxy
      app.kubernetes.io/instance: oauth2-proxy
  template:
    metadata:
      annotations:
        checksum/config: 5c59d0ecaa35338a8583f7ec6a8f2c52360739be7f35505fe65237f7b21bdf9b
        checksum/secret: 9eb46bbdefd5cf844a2c4965b1241a7177addaa7c07789e7873ccda6b0104111
        checksum/google-secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        checksum/redis-secret: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
      labels:
        app: oauth2-proxy        
        helm.sh/chart: oauth2-proxy-10.3.0
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: authentication-proxy
        app.kubernetes.io/part-of: oauth2-proxy
        app.kubernetes.io/name: oauth2-proxy
        app.kubernetes.io/instance: oauth2-proxy
        app.kubernetes.io/version: "7.15.0"
    spec:
      serviceAccountName: oauth2-proxy
      enableServiceLinks: true
      automountServiceAccountToken: true
      containers:
      - name: oauth2-proxy
        image: "quay.io/oauth2-proxy/oauth2-proxy:v7.15.0"
        imagePullPolicy: IfNotPresent
        args:
          - --http-address=0.0.0.0:4180
          - --https-address=0.0.0.0:4443
          - --metrics-address=0.0.0.0:44180
          - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name:  oauth2-proxy
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name:  oauth2-proxy
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name:  oauth2-proxy
              key: cookie-secret
        ports:
          - containerPort: 4180
            name: http
            protocol: TCP
          - containerPort: 44180
            protocol: TCP
            name: metrics
        livenessProbe:
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          timeoutSeconds: 5
          successThreshold: 1
          periodSeconds: 10
        resources:
          {}
        volumeMounts:
        - mountPath: /etc/oauth2_proxy/oauth2_proxy.cfg
          name: configmain
          subPath: oauth2_proxy.cfg
        - mountPath: /run/secrets
          name: secrets
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 2000
          runAsNonRoot: true
          runAsUser: 2000
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - configMap:
          defaultMode: 420
          name: oauth2-proxy
        name: configmain
      - name: secrets
        secret:
          secretName: oauth2-proxy-secrets
