keys:
  # abutt - converted from ssh-ed25519 via ssh-to-age
  - &abutt age1kah6uk67hrf2g0805ralt05v83ry9ay4pf8h66mm0wlaq3zsdqqsk66myg
creation_rules:
  - path_regex: talos/secrets\.yaml$
    key_groups:
      - age:
          - *abutt
  - path_regex: .*\.encrypted\.yaml$
    key_groups:
      - age:
          - *abutt
  - path_regex: .*\.encrypted\.env$
    key_groups:
      - age:
          - *abutt
