keys:
  - &tiberius ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICnQDGTR3J244BlVZ3u0I9l476XRxlv0DdmREzTku3Ib abutt@tiberius.com
creation_rules:
  - path_regex: talos/secrets\.yaml$
    key_groups:
      - age:
          - *tiberius
  - path_regex: .*\.encrypted\.yaml$
    key_groups:
      - age:
          - *tiberius
  - path_regex: .*\.encrypted\.env$
    key_groups:
      - age:
          - *tiberius
