keys:
  - &tiberius ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICnQDGTR3J244BlVZ3u0I9l476XRxlv0DdmREzTku3Ib abutt@tiberius.com
  - &gems-cluster age1r3aas35hvsswx2q04f2w7asg5373wvdydr4lufgdptjfq4hms9yq3au5rx
creation_rules:
  - path_regex: clusters/gems/flux-system/age\.agekey$
    key_groups:
      - age:
          - *tiberius
  - path_regex: talos/secrets\.yaml$
    key_groups:
      - age:
          - *tiberius
  - path_regex: .*\.encrypted\.yaml$
    key_groups:
      - age:
          - *tiberius
          - *gems-cluster
  - path_regex: .*\.encrypted\.env$
    key_groups:
      - age:
          - *tiberius
          - *gems-cluster
