clusterName: gems
endpoint: https://192.168.86.230:6443
allowSchedulingOnControlPlanes: true
patches:
  - "@./cni/patch.yaml" 
nodes:
- hostname: gem-master1
  ipAddress: 192.168.86.230
  # talosctl -n ${ipAddress} disks --insecure
  installDisk: /dev/nvme0n1
  controlPlane: true
controlPlane:
  machineSpec:
    mode: metal
    arch: amd64
  ingressFirewall:
    defaultAction: accept
