apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog
spec:
  imageRepositoryRef:
    name: blog
  filterTags:
    pattern: '^(?P<ts>\d{14})$'
    extract: "$ts"
  policy:
    numerical:
      order: asc
