version = "2"
bindaddress = "[::]:8443"
domain = "sso.abutt.dev"
origin = "https://sso.abutt.dev"
tls_chain = "/certs/tls.crt"
tls_key = "/certs/tls.key"
db_path = "/data/kanidm.db"
[online_backup]
path = "/data/backups/"
schedule = "00 22 * * *"
