apiVersion: v1alpha1
kind: HostnameConfig
auto: off
hostname: gem-master-0
---
machine:
  network:
    interfaces:
      - interface: enp89s0
        dhcp: true
        vip:
          ip: 192.168.86.69
  certSANs:
    - 192.168.86.69
