apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blog.yaml
  - cloudflared-abutt-dev.yaml
  - cloudflared-emilyismy-love.yaml
  - jcu-site.yaml
  - kanidm.yaml
  - valentines.yaml
