apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:KttRHr4V40WwzS8Cu21KBJRkTBd9d1es1hRB3aBvEk0OBuezfciEmnKbRiCz/nEZcYJ09c4nrM/W17it1v7uyS45rKLmch/9QX6tDPwiWKHdIfVsZ6w0Pnk1p5qVWI6kTTi6ZuqcYBKtKypI3Dn0Uo2fJBt4HXl3prNJS4+3gyTPHsfeMq21vrhXHvIBWxHIK/5QRkNkaaAA1tyJXDY2oOyTvrEw8wtg5x952tJ3N+01QMsKEyjQQQPIi8TpivgTrSHU82gCLA/IFjuRZ+Zurdi9itjxIeAZSyYvJSUcYIEbQLQlU0vQ14slLuI=,iv:62BCLKkNotasdbv8PgAjs5P6CJg7El5R//q9Cp5popI=,tag:bt18Z4TiL+MNftzWfM5IbA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICnQDGTR3J244BlVZ3u0I9l476XRxlv0DdmREzTku3Ib abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGFJNmU1ZyBkMWlW
            aE1jNUZ6a2duWTd4MVNkNlVEcnpseUtNYVNVUlBUK2hMRXNLNjBNCmZqdHRDNTFv
            eUJNVW0zT1V3QkkwUmFLZStwZ01hcjdJZU9Va1hLOU5raGcKLS0tIFdVVGo3UWFK
            ditBVGQvalMwWUNrdlI1dHVRYzBrelJxTVVkUHIrNGRaTWsKxC4bt6dXaT6ZexLN
            3GeNoswXMgeagWb06OoXdKoptS/2ApqIirzn2dta9oHg3Py+S2fFPTIQiHWif8ZS
            0FzCEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x43sjuly4kjrvmn07f8r77psgxa9f49d2egcmgl4aqkl7nmnafzqs56wzq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNlNmc1BFcGVIRFR2bDEx
            UU9YcjJYZjJjYzFxNlU0ajhHOU1kd0Z0QUhJClR3MEc0UkZBck9LOUxpLzVuaEtx
            eVpqZzluZHB4UlVKR2UybDJsaGNRdGsKLS0tIGJnTkJ4VnQvV21ZMUdFVDVlTWFY
            Vk9SOFNpL3I4NmUvVVQvNTVCakxFeEEKkZfIX8r3Yeihz90ANuiJNyKjJS9QJhKi
            KCaSTXGNuQA2C3JNOQV34+m9sZo0kc30c3+KUCjdgGLtNpQnmhENww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPYkXD5kuITfXNUgU+yzirklzKXKRlT5ZKYwKo03lzzz abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGg2RGpKdyBmUTNN
            QjBORnQraGQ4Z0dFVXlHUEc1d1RrMDd2dzVUZ2J4d3ZaT25HWkJzCnVmZ2JYU2pW
            TjgxVFhmQVRUbUh3MWJCMmNOR0Y4THNHTGRhNFp1bU54YzgKLS0tIEhOdXFPUHhL
            RFZIUEQ0VFBlNkRrbTNFM0ZqdEVUWXpiMzdtQ3FiMTZ3Wk0KH4tXc76M2rt0xDeZ
            F6aaMTAWwuhwhc/jAF6n+LyRmr6VmAJTQnzD6I08hqp1Jp7hkf6vipQ/0u9YhCsV
            lEyXKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII+cqj41D3k8Dk9Bz4l/06XVkkxMJIpg1orvuf56/Hme
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNSbC95dyBsSVVX
            VHlLU0FnNWFzbnU0OFlidkxlYnNmVitHZms1eDZVakx4U2FBWjE0Ck5UaG5lbklO
            SkgyMExrQ0hxemw0MGZIYVhkMXQvRDNXYittQjh1U2NtaEEKLS0tIG96emo2elEw
            ZFlHRmN0RmliWTR0NTIzaCtrajAySU5RRlhrdkJLQXJsTEkK2dnbvgE+tsNeNYGF
            8/gJi/Cktrnw28n91h021m1HefW7JwJsMvpi13lbj7VUIRLNUNnlkNOe+SviPZSd
            E3JTYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T16:37:29Z"
    mac: ENC[AES256_GCM,data:ked2xg7EL1BMqfahA/Z/sPpWizepaZqilgs38UMCJwuPYaOfw8iv5pi9cZr7MExmPwAxxm9mEPeIm8hZ16TTCaYaAF5xxVXS0/FaxkdF5S5tbqN262WLsXBqxFQNrR6AN5Os9sRl71ZiKbW2GJlR2domBGlFt3rnw2+94WJTMls=,iv:jo0XmMIaPT3/cV10YM+8qh5HjoGpchE2IIWKVrq2Gug=,tag:5iKGKEtfkzzyAahVlqnNQA==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
