apiVersion: v1
kind: Secret
metadata:
    name: jcu-secrets
    namespace: jcu-site
stringData:
    secrets.toml: ENC[AES256_GCM,data:Py9QuwIM51OGZ3+YiLQOLC55ts86sKBR/GXu+sf4JpuwHSUkoT9rDoiS9IlgPZD/5E9r6Vh9U46F5xk5/6YIkdF4cy2qja770YHmgmFJKREh/bL4RxNZHGjYb8R2yqVjOWFeiKRWd3JAo3ajnSEk6OdIB8Top0lRQyE+wyLqsmSBnX2D7ncqcFJ/9U1+ms0oZ2CJH4aD0JEynTqXBtkJ6UtaYaK4SPGDfSUi3aoYdR2H+xeNIhvRWid71xLasHD8,iv:et4vohG83czY17P9f7eEflGya9eKzsqI8WOHVOh5qqA=,tag:Ow+4W/5Xkl+QBNe8mewRfw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICnQDGTR3J244BlVZ3u0I9l476XRxlv0DdmREzTku3Ib abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGFJNmU1ZyA5MVQz
            R0hvVVlrcnFscHlwcVJlL0xQUjRtZk02c2RnY2pvd0V6cDVJUkcwCnNiVytGQ0V4
            Vm9TVUM2Qm5hdkJBTzg1UGdsMklXT0pYUEx5SHBYSUtBQmcKLS0tIHRLdm1DTEdU
            MW1rY0hmNGVnSU1qa1g5Uy8zNElzRXY1cWZ1TjNxL3FMUGMK4yidRTh7mHF3QvEg
            a5vTTe0HLpsNirqd4EjJ6FjdKoFsDR/5PwVLL4J5hRdM+P8in5RNxWrCoUmY7469
            wHWr2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x43sjuly4kjrvmn07f8r77psgxa9f49d2egcmgl4aqkl7nmnafzqs56wzq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TUdRTk5rNm9TbGRwOUgw
            WUZPVit1WnFkb0l3TUU2VEc1QUJla0E5QWdZCm45TDFVeCtOUTd3ZTAwSzZGVE5P
            UUFrN2xhWFNxSlB4MklidkVkRldUTVUKLS0tIHhTdFpUVWpDNjRWaVJoTVJuUGZM
            c1FubU91L0JPVEp6Zm44Y1dHbFBGNmcKp10Jnw04pSWwu4ZZpW1jskJgbv7mbW5J
            zTPqqnvdpIOxlmKUUyw5ucXhxyP+0Vr3XzmaT4qJJt9z5NGSqyCt+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPYkXD5kuITfXNUgU+yzirklzKXKRlT5ZKYwKo03lzzz abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGg2RGpKdyBrZGZP
            cWhQOTlGVTNEWmwzcCtNM0xsR3p6NUVOdUtKVnFMNVZhN3RpSG1VCmYrN0lYcUl6
            MWN4QU9pelpRYVM5N1Z6bmlzUUxjbmtrTExva0dQY3Z1WjgKLS0tIHdTR0l5STF2
            Vk9NcVBRTWE2SDk2MXJBOUM0MzZyNWMwZnVyeVlDcXhLMlEKXDAta0iUQAP1to+J
            oLbZDIuQBdGwhVEoLTM2WnUxLsNy7+qk4EjQ3cRTVyAKT5pnilNKhSNIDUFBUyWO
            XJOoug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII+cqj41D3k8Dk9Bz4l/06XVkkxMJIpg1orvuf56/Hme
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNSbC95dyAyaHpk
            REV6OG5PNEYxSlZ6N0FPbmJKeWV5cVpnOHF0N3N3OGxrMkc3ZURnCmNXSXNjZnF5
            RTZkSnBISzN3VHQxQ1N4R1gyclVmczdiaUN5dmFFTmJDaVkKLS0tIEtIZ1Z1S2VO
            aG91OFh6MGpDdTlIa2d5TElDcVZhY2lLc2U1aFhSNXRxQTQKIEavZQPZSar8sRp3
            06MmUnmnse7dZOJDRgpWV2kEvqnCGuulKfxcqJJr3uBwA7QYqIqa1OBcyiG2QhCn
            jbkeWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T19:53:47Z"
    mac: ENC[AES256_GCM,data:HrNy6lsyq5ECpejPx3Eia20uHCuFpIlqj9fo0cS6QnjL3J6/mEQxhVgYkZ9ENa4reKJ3D5OHhxhbugOifPDEn6bUroZ0DIf9OQHnRGNYpLHzimUVxOL8rhj4MqdTTZr+nNiUsOtv0cQ7MRl/8zhtXU5n5p2KXJ8rv88+3H2Nrr0=,iv:fT7z4prdPMVjKwechW0o+rtNWpJLNiBLhP/hKOTgxV8=,tag:2wtfbW2RR+A0eu6az+6R3Q==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
