apiVersion: v1
kind: Secret
metadata:
    name: jcu-secrets
    namespace: jcu-site
stringData:
    secrets.toml: ENC[AES256_GCM,data:TQ+Bn5L+9tvbEhGo1YbFdB1FUEdnJJKvcFOMWm256VMZTl9Ld6yqFlfGvoYIInf/hoMfBM3JtV6JyMs0BXRc0Jncq8bzQfHcM7T7BpuYuNxtcs8EIZTjmTLYCujvh4ZX9Ds+VztH2XLU1Mmfi/EnKJeMpXTuPZ9sFyWjHpY5o9a/v9tO5fSQutSnB4XK9O8LrFzvv/ho8M2KwETs8a3zxhoshqdtOAz6Wuwb/m3X8exdQ5UjS9ZdFl0SI3qvKKectQ2TEB8s+Yvu9PzG4VJ3DHlwcZM5F/neYPdUMCQo9DizFQFUBL4J5K5SfiqffdoVX+08Sifr2aCJJd0vbm+Q3OolSE5N+N3oHPZ6UFwDsrvzj66lm1aBAdh3u4oysKn60mKZ/PE7fGMJnmRfhsGJE+UIQd6olCKG4HaeooixzSd3COrNNxLjAJRAOhevAx8p6M4Cqjs/Xd6abwBeyd77fGkYqA78kYwsyCX51bULyyCwkYXtHnjPKPlKA2EB2DFImQBUPkSd9EVkVn3oNGtCKwR1r0iBX3/MbKSdUSILfcDh9CzzMvEJq/lRAuyBu14gmcVWBGuS3FNRT1pvhl72plqTrCciDTptgVc02W6NDpb3VLLD8aBecP3pW4VFoSuOKPKMRGHmFi8G,iv:ZAl6R6qlSB6m7PFAw8pyo30T7W90d2DNwyTSBBFID6o=,tag:MwPbeXu3qX0O6nsXogkPSA==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICnQDGTR3J244BlVZ3u0I9l476XRxlv0DdmREzTku3Ib abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGFJNmU1ZyA5MVQz
            R0hvVVlrcnFscHlwcVJlL0xQUjRtZk02c2RnY2pvd0V6cDVJUkcwCnNiVytGQ0V4
            Vm9TVUM2Qm5hdkJBTzg1UGdsMklXT0pYUEx5SHBYSUtBQmcKLS0tIHRLdm1DTEdU
            MW1rY0hmNGVnSU1qa1g5Uy8zNElzRXY1cWZ1TjNxL3FMUGMK4yidRTh7mHF3QvEg
            a5vTTe0HLpsNirqd4EjJ6FjdKoFsDR/5PwVLL4J5hRdM+P8in5RNxWrCoUmY7469
            wHWr2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x43sjuly4kjrvmn07f8r77psgxa9f49d2egcmgl4aqkl7nmnafzqs56wzq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TUdRTk5rNm9TbGRwOUgw
            WUZPVit1WnFkb0l3TUU2VEc1QUJla0E5QWdZCm45TDFVeCtOUTd3ZTAwSzZGVE5P
            UUFrN2xhWFNxSlB4MklidkVkRldUTVUKLS0tIHhTdFpUVWpDNjRWaVJoTVJuUGZM
            c1FubU91L0JPVEp6Zm44Y1dHbFBGNmcKp10Jnw04pSWwu4ZZpW1jskJgbv7mbW5J
            zTPqqnvdpIOxlmKUUyw5ucXhxyP+0Vr3XzmaT4qJJt9z5NGSqyCt+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPYkXD5kuITfXNUgU+yzirklzKXKRlT5ZKYwKo03lzzz abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGg2RGpKdyBrZGZP
            cWhQOTlGVTNEWmwzcCtNM0xsR3p6NUVOdUtKVnFMNVZhN3RpSG1VCmYrN0lYcUl6
            MWN4QU9pelpRYVM5N1Z6bmlzUUxjbmtrTExva0dQY3Z1WjgKLS0tIHdTR0l5STF2
            Vk9NcVBRTWE2SDk2MXJBOUM0MzZyNWMwZnVyeVlDcXhLMlEKXDAta0iUQAP1to+J
            oLbZDIuQBdGwhVEoLTM2WnUxLsNy7+qk4EjQ3cRTVyAKT5pnilNKhSNIDUFBUyWO
            XJOoug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII+cqj41D3k8Dk9Bz4l/06XVkkxMJIpg1orvuf56/Hme
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNSbC95dyAyaHpk
            REV6OG5PNEYxSlZ6N0FPbmJKeWV5cVpnOHF0N3N3OGxrMkc3ZURnCmNXSXNjZnF5
            RTZkSnBISzN3VHQxQ1N4R1gyclVmczdiaUN5dmFFTmJDaVkKLS0tIEtIZ1Z1S2VO
            aG91OFh6MGpDdTlIa2d5TElDcVZhY2lLc2U1aFhSNXRxQTQKIEavZQPZSar8sRp3
            06MmUnmnse7dZOJDRgpWV2kEvqnCGuulKfxcqJJr3uBwA7QYqIqa1OBcyiG2QhCn
            jbkeWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T03:15:47Z"
    mac: ENC[AES256_GCM,data:2lnIWhEFSjQtWszd4e4smwq7/vFJINTcPaKRX/dWmMHtvYcCmuFtI/UB1/6C66uXlpucKTCnmsCOPXGWsQ9UApKpKUAcYVK9QOYIkKZGHiNG87P7aRgo3OHEQIjML47GrRMmQMKTqq9rFzwY/MWpr83w3pAXuivT4p8Ju/YcfZc=,iv:pH5ib8FtxxL7KvzVzYEShZDqUWUYQQVJLVbkB8VAGTY=,tag:a/Unz+OUFB4F+FH5YUe33w==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
