apiVersion: v1
kind: Secret
metadata:
    name: jcu-secrets
    namespace: jcu-site
stringData:
    secrets.toml: ENC[AES256_GCM,data:MRW1+WNjk32v9AL9MLi5fGrBNohO+RWJfgOGb8RJuAFzxb11DvRpqQeEKV2skuOl/eK+D7KSqkRvj9tf9DaWHGAte+Oe8G1Wds9XBPbzoAKxjd41lvd1r0YbZIgbhRfJgzqmL+qGDu5YxtwPiku6LnqMIU1D4hC9eiY2shiIdMUmNemsbZDF1yLyJn2LjfxDTFfmPlqk2wFUDtclxGS0BrhcA660okLwqhx9dKfzfHMLukyUieCroas/LLaip2hmTvNDk3pqqroldVlJBKQXmC5OfH4aterA1GqjufWSStje/+jCVvACdUShY4teejFSMgC4yti0svPmaqTNTm7Sd7ps6gb8LuAKt4UogatP7IGWS4g7CBxWfCTDkow+QzMOdvPngJXCZmrlNKUJmw36s4/YhxsGxhKPSbQytWS+nPob995emHtFvg3mZzutUxviNFAFES7z4Y4=,iv:67JpoztwJX94Mjs2BdT4pwOmT9xj/FjbKx76ZN8gees=,tag:Atv7Yf5hCH9gCUe9MpTfaA==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICnQDGTR3J244BlVZ3u0I9l476XRxlv0DdmREzTku3Ib abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGFJNmU1ZyA5MVQz
            R0hvVVlrcnFscHlwcVJlL0xQUjRtZk02c2RnY2pvd0V6cDVJUkcwCnNiVytGQ0V4
            Vm9TVUM2Qm5hdkJBTzg1UGdsMklXT0pYUEx5SHBYSUtBQmcKLS0tIHRLdm1DTEdU
            MW1rY0hmNGVnSU1qa1g5Uy8zNElzRXY1cWZ1TjNxL3FMUGMK4yidRTh7mHF3QvEg
            a5vTTe0HLpsNirqd4EjJ6FjdKoFsDR/5PwVLL4J5hRdM+P8in5RNxWrCoUmY7469
            wHWr2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x43sjuly4kjrvmn07f8r77psgxa9f49d2egcmgl4aqkl7nmnafzqs56wzq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TUdRTk5rNm9TbGRwOUgw
            WUZPVit1WnFkb0l3TUU2VEc1QUJla0E5QWdZCm45TDFVeCtOUTd3ZTAwSzZGVE5P
            UUFrN2xhWFNxSlB4MklidkVkRldUTVUKLS0tIHhTdFpUVWpDNjRWaVJoTVJuUGZM
            c1FubU91L0JPVEp6Zm44Y1dHbFBGNmcKp10Jnw04pSWwu4ZZpW1jskJgbv7mbW5J
            zTPqqnvdpIOxlmKUUyw5ucXhxyP+0Vr3XzmaT4qJJt9z5NGSqyCt+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPYkXD5kuITfXNUgU+yzirklzKXKRlT5ZKYwKo03lzzz abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGg2RGpKdyBrZGZP
            cWhQOTlGVTNEWmwzcCtNM0xsR3p6NUVOdUtKVnFMNVZhN3RpSG1VCmYrN0lYcUl6
            MWN4QU9pelpRYVM5N1Z6bmlzUUxjbmtrTExva0dQY3Z1WjgKLS0tIHdTR0l5STF2
            Vk9NcVBRTWE2SDk2MXJBOUM0MzZyNWMwZnVyeVlDcXhLMlEKXDAta0iUQAP1to+J
            oLbZDIuQBdGwhVEoLTM2WnUxLsNy7+qk4EjQ3cRTVyAKT5pnilNKhSNIDUFBUyWO
            XJOoug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII+cqj41D3k8Dk9Bz4l/06XVkkxMJIpg1orvuf56/Hme
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNSbC95dyAyaHpk
            REV6OG5PNEYxSlZ6N0FPbmJKeWV5cVpnOHF0N3N3OGxrMkc3ZURnCmNXSXNjZnF5
            RTZkSnBISzN3VHQxQ1N4R1gyclVmczdiaUN5dmFFTmJDaVkKLS0tIEtIZ1Z1S2VO
            aG91OFh6MGpDdTlIa2d5TElDcVZhY2lLc2U1aFhSNXRxQTQKIEavZQPZSar8sRp3
            06MmUnmnse7dZOJDRgpWV2kEvqnCGuulKfxcqJJr3uBwA7QYqIqa1OBcyiG2QhCn
            jbkeWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T13:45:40Z"
    mac: ENC[AES256_GCM,data:O2EeZdGEbcKe2b0qKJhHb5C8gBUdS3WZUlo056RoyTTNkfuqSuhrkNYYfb19BFgSz5Y1iBc9FVm2Y6HDgJ5ygV16gjEScN2iuejEZuhColiH0BWWEIhdAp2g0sPFDK1//vEcX1ycsfDw7qiQUHNyar0z59sxYz7Rmz8MntKBiVY=,iv:kVNu1GrUk5NGnLvW9qYlrss+G+Y6Ipb9SXX0hNAlye4=,tag:oDm+IXTl/tplmCuecfEwxw==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
