apiVersion: v1
kind: Secret
metadata:
    name: jcu-site-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pcLswkJBJ1gznnqxtI8i/lDVjaMvD3Ly73jkTDV594/RbZezFE99YPszUZoDP9HWSq1tYMv5xO5FWOBivN94J7hHunapNqMmVNOxYPYHsVy90wEkkyWFXtgly3Ilyzbjf/yxPXvfd4WDZ8CgWhHc/UBOsVhJaRUqFocpu6v06euKb8uuqcUM3TpmxAeFNLvwL/KYD1Tvlf9J9SeBurpLLExsPV/6stE9W4qg9PXvRdbxLzmsuquAD4MoOeuKqbRGwXnSStZCGgx4LdQuQMiMnhO/9hTPAM/kAnfq4N/aWjVhDFSvmuSpflwSK39GU1DmePJCrX73Lyt4NFsq20SI/e9v5hWxomItGj1uV6kfvxHvprFFef2IiK5ek+S322mqAyvx3jyj6NKbwIG5DSTJgXqXdBQq2rMIzT7rkKiMfWX2krFYZJMynrOjSkJHrKMazsh6FOTKgSFsiQlGLK5QWGnDjwKrs6Q5dLd9dbHeFAekFyxzlb5xUhGKlBCApQDVtSr4XpH8XBxGR3SKnOS0+AY+cfoX5Ise+gf5,iv:IDKzMwAG6Hy6DtaL2kpW+sOCTw6lEJvvSMhe8kZaKG4=,tag:SwpnEDQDwuQSXENDi2w8SQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:f2wX95H3BIl3MZkIfk7+mBldkHxasONAjVfsRkf/8PfE/APkAEUpaDW7j6ifUCL3YeYDEYKRRjVG1cQxTje8czAUiUXZzXDBe2uQQAH0e65sCOfsZiMRNwWR6UpyMl7GXHhAj18tGHDNNIQ0Z1H6Z4Tj2CYbWWSqSLHsjwN2HYBSJ17865sLrVwrMFJHgE14YqFqhqXqwuMlsjNhn62nHL2qNHXm3Lzczf4ggaR0v7pXxdmQ9St4ZBkD74iQmoJ/AVDlEuSm+K2tsloqd5TD/UE07POcwyOPO7F8tsrXkCUb0oklV7tbaYs1fiORqcKCL1v9/I+HTUwACsNFvYN8IUYeLPkT1EmN4IKOMgcK6TzKdEXUnIpvi3vdA+TWzHpRhYEyFiQTkZj/cImb74NNI0NUjJ4Vo9KDx5rqELFfxvxQSV5jtRZKGNAesWsBLDJ/2v07zebclpiOjTPTw7zayal9uDsShfUnXcy8wd17n+m1CCrnp+oHGCA67sb519keiffWqdoqynH9eeCHhRljJryhHRfJnBu49uzQyQL5ZyV4qqnk5lYtOPIMazBGdukPAeeIMvkMOMX9aHmp1EUFO8fDXlvBpkCcnnUH2fRFi/oREFmPbZpFmQP+n8udsknva5pdoHb8nbY02JbJTiCf6lBH1bNmPTNSqmhIT6d6+NsffSNitnPeRjrw7AFDDUqrpfNoPjedT2TwNJnf8NhnN1eAOmTPgr/afpwYLr4LnUwNJVvm/Q99gPvt9xLDWfG/VcIh1pxDt+icRReenwoGIv4yWmXkiWJmgmQqnRclKufJ9wCl+QHFqmq6NpQ3JtV/VU1SAlIi/kvu87NU4bNtKrUB2DecqYbn3IhsordoTRlabY8f8YHL/xoQmNF4btMdPCTxG/6982mpyHFOTO3NxhgHKhOULmJkm/33zgQr6PuLo52V5OnU7T9eQ/nH6FUaQGudzWy2i1QTIC3EogZRS9x2D6+4tChduGUCGPfkf8toyhnBH0Ga2wBv6VRooHzbMPLiOf/PS2y1Ddj46rQuEHyvnnEoLPrHeAIo45ivJtvGnqeaGgS549LMRJsL6x/rFStaLqGWTVNAh5PMJwPTUYoaCrmrKfmK1R26HraMWordSAr3mMXq+5wAAnczv+kxj6qQ9QtSgec7m/SaDWSy1QThVjtvXsR3v8Cve712NmaqV14VQyXHoF44BrMvqY8xMVQJ9Wc0YoJZo5Q9GOU1dFI4+l7RZ7suAnOzqYPNYvx3q9emtJgq/9biB37tmGPj3xCraomb6u1Gtnv9jz8WdDQTjoi67sWcekRANQ==,iv:V11PHiFsr9ndB6m1pi2v6JMK5z53P2/S/aO7lWQW1lI=,tag:B72o4RKdSWMq9BfUTIjSKg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICnQDGTR3J244BlVZ3u0I9l476XRxlv0DdmREzTku3Ib abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGFJNmU1ZyBzUEpI
            OFFuNTNUekZ5R1haeGtVRm9mR2MzVGtzN1U4OUhVenZQREFWWVc4CjN6VHZtN1VO
            TzJnNW9FM3lOQTd4cjd4eW04NmtEOTUrRkxic3ZFTzQzSlUKLS0tIFA1QS9OMU9R
            TmFTcWRlRjF1U0VRbDdWTTQ0ZFRiR2VWZExrRjVXN28zSG8KmbVIMieh+5WVIwwM
            +c2vlnc6tsO8Rk6l3E4td4QER2os6hqJrtwClm4xeGurQOl4UPM4IgYf2aYZrhTO
            JFcAoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x43sjuly4kjrvmn07f8r77psgxa9f49d2egcmgl4aqkl7nmnafzqs56wzq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVENjTHl0UlhCbkJ6ZnZy
            cFd1Zi9nVmNxVGZEVTA4WVhjRldiMEEwc0JRCkk3TTNpWG5yblpYZGVLdDd5THNx
            bVBqYndDMStuMVVjeG40MHQ3czRzOWcKLS0tIEJyL2ZZMm5qTUszTmlRbHRmUDNM
            ZWRGUmowSndxM0g3R0k4Yk5HNXhuNDgKjh4+b95g33zENfZzkWXG0rGNhVhEevdx
            fa9qxOcvrv/X2KqLtbsF6j3Ddw72HHqnHPZEKYzfqymkZvyMCNuwRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPYkXD5kuITfXNUgU+yzirklzKXKRlT5ZKYwKo03lzzz abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGg2RGpKdyBlMC85
            eW9CdjdLMW90bEpZdzJJKzJQYnRkRUxZNGd2bmM0YmFmOWJwU25JClA5MlYxRTBm
            VzBQOFREZUZjTWozenY1NjROd2FxZDA5aXVnVGxSZVBWdk0KLS0tIDN3T0Q2dGRk
            bmhsT2I2V1RMVEVianJyV3ZaWXhWOXZ0TlY1UW41MnpIalEKmP9kEfcCCDcKcvKL
            eqrwitnxQlnEHb4Nj08nIl86zBXTaPNGn7i/V9ldBM0W4721VdiI/eEIdfTqXih/
            /A8y9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII+cqj41D3k8Dk9Bz4l/06XVkkxMJIpg1orvuf56/Hme
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNSbC95dyAvQXQ0
            MmZnSjhkRHl6MkgzRFBMeUlqdFhmOTN5QTBPUFZ3Y0t4aUNSOVVzClRRSzhaVEx0
            dHZtZnh3U0VmaVFwYXpDY3ZXTEpicUorL0x4Z1RGVzRRbGMKLS0tIE80MEl2azZX
            emNlNGJkSGFrcHRQenBQTUZleVlibVo4ZmY3OFFLMVhvY2cKTFraDR7KVZw0XeUc
            16QrFUY3RPzt0lygYrO9pcD6XXrBge6AMzGHh4H6LgOSebWOQ6Dj2hWTGwy0nGZK
            WyHCKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T16:33:45Z"
    mac: ENC[AES256_GCM,data:NUKTEBbIv6vG9oyBRY1fVhfrDtajq605JLL/scHsCMq9ST3//gTTFOal97ThiltIyst8CRJjbPgZ7L10HkQ0t54/CkNlaiIyVICWa7BgTqUnBGPd3jKG8wG4KQL0K1gkKPC3ZPA1PbNVWCh84/TuzIOfPuCefiaf5HZhmfQZjA0=,iv:JdM2XMRO2U2y1QnZPX1nORQjLN3O4UPugCRuEElSJwk=,tag:dXj+QqBm4NRoUxyybzomQw==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
