apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:SDGhVIbVHOQB1ev4EkD2aiAJEzdF7p7QZeA+aoEGPKSKi1aNzwMcrj/60cAcVrMKRcgQf8+IN+PeC9kXk9mgih0EkzrDpB5b50VvtiRdq+uH+Tv6Ezbi9wmne4hRUK41dcIjfkaoDZdqL+FRbJHjLfbB9Hb50XJKHnQykmfCieHqbiZLL06YtFhFrxcLFud3/DrkSGTwTMsGeGvJIlRaWrztnaa3u941kvZAjSjJk4AkEaSyIiUwLzjO2RgbPDXsxBFjd0u7bszDjWO6OsA7GBAt/4UuAGaYyKCt1MAN7eLcAIHPCv0sMynr+pg=,iv:ux2C7Lus4tbeesah5hwKTqB/S6qMQcTpdaGULHYfqSM=,tag:1iu5PDfciHLAsUkvmvX0lw==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICnQDGTR3J244BlVZ3u0I9l476XRxlv0DdmREzTku3Ib abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGFJNmU1ZyBxU2wv
            RlhzTVZHY2hEZ25WMDNsTkJaN3Flc2RCbHNMWVVxbWZ5bHRyNkRNCmVJWUZUUFZ4
            SW81NmV4Ly9aUDZvVjNkVFRkNERiSXNjWE9LK2hxbHJlNFEKLS0tIGluRUMrb2Fx
            VlRvSWszUWl0ZjFlbk9nTERNR0xBNzJOVk5NTjQ1Uk8ySUEKE6gOrI3ZzZ4eSqkh
            eYP0bbKlf+5y/xvoqOE4XDrUP8gz9Shr/lkeVbEC35biJn0+rdIGuyGzzzESGE19
            s9LLEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x43sjuly4kjrvmn07f8r77psgxa9f49d2egcmgl4aqkl7nmnafzqs56wzq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Z2Jsem83Y1NwRmhiSHpH
            ZTJFNE5HcWZmVS94TUcrUUtRcEVtcHQ2WFdvClFxNEkzeGM5c1ZuOEEyTG14cUNk
            bWlzdlhCdlNnQnVuOXlYM01hZ2VHaFkKLS0tIE90Ym9tQW9IamJROUloZmRBS0sz
            d28zUi94OUQyZEkzdjhHeGV5NG11NE0Km4otcixFv6uFnSlraY0kSzvW7fYTqDEN
            0Mps8OsK4C0SgXib6wXQR68A30k4+nl3pTBMB3wcx+c9pbKy6WhrzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPYkXD5kuITfXNUgU+yzirklzKXKRlT5ZKYwKo03lzzz abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGg2RGpKdyA4eGFk
            KzRQb1pzM28zd2FLQWQ1NnZqWjBLNFBHMWpRRHRNNWdIVE43d21NCmhxeDRqSWpF
            YlZQN3NxeWNqenp3RGFhUGJSd2VSR21PZzRMYW16bUJ3akUKLS0tIFBmY0ZXMDNl
            dGx2akVrSVV2aTRSbVd6NWF2ZjdTejFuWFZ4a1MxbEpVUlEKGczzsuHT1G4EwCJ8
            0KvXJKZl/mtv63wJZzQj/akuQYN/pGy+oPBVSqBGQMgLjtFujSUAghDL//h+n0KV
            cjhy7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII+cqj41D3k8Dk9Bz4l/06XVkkxMJIpg1orvuf56/Hme
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNSbC95dyBhREpX
            empQRUNxMnM4ejhkUG9sclFsQjFqYU0ySk9md3FicWZwR24rblJ3CnpJdEd0VG1r
            WldzRlp1aGRISFh3aXlPTUltaTBkTTJNc1ZXYjMvK0ZNU28KLS0tIENBNDdUTGlY
            TmQvaFF1Rm00VEVVbXNwbDZMYlZibmhVTUJLUWs1NWtkdkEKm80Tuo0sYfUvysHW
            BoeuJG9eEyXKeCykVu7zmxbDgVHcbAklXJbQWqr+BYr2XZOzXV+gijlLXANiy6q2
            9snX5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T04:17:50Z"
    mac: ENC[AES256_GCM,data:IDIQHShnIJRuLxKhGMOGPdfOhPGWfzio3689l7pNBx84PIx/sRIeSZA0MvyxNz+IsE/HSQpZ7CbOjMMnweXdeRef8Lc8f4tLDu6rtj2/+9O2XAkIFZ2ZyDMTar0JPaJBsqa4OP8NvQZgui29MHmjsAMylqnB03uXrcsuRa718zY=,iv:e5ogAqMTgisjQtw7pm8o22tTp73ERfyWGFUGx1cd2X4=,tag:JIfO+9caWMSnQU1R4J9y7A==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
