apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: sops-age
    files:
      - age.agekey
