#!/usr/bin/env bash
# Display available commands and tools

echo ""
echo "  Gems Homelab Cluster"
echo ""
echo "  Run 'nix develop' to enter the development shell"
echo "  with all tools and commands available."
echo ""
echo "  Available packages (nix run .#<name>):"
echo ""
echo "    render-helm      Render helm charts from values files"
echo "    sops-reencrypt   Re-encrypt all SOPS files"
echo "    bootstrap-gems   Bootstrap the gems cluster"
echo ""
echo "  Tools in environment:"
echo ""
echo "    talosctl         Talos OS management"
echo "    kubectl          Kubernetes CLI"
echo "    helm             Helm package manager"
echo "    kustomize        Kubernetes configuration"
echo "    sops, age        Secrets management"
echo "    fluxcd           GitOps toolkit"
echo ""
