apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - clusterissuer.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: cloudflare-api-token
    envs:
      - secrets/cloudflare-api-token.encrypted.env
