apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:yIeG4bvEF/Fv96/iIQA0INBiCkLeEgbUQq3uZBlPwgzGxnEBgNBkJJxW3lwY6aItTMKDNm9Zhkb3ilGCTSWae1ZJcJbbbsy+4deqsRahg8mduwCoaFYBx2qsb3UJaA5f3vLw9aQp659Q0lgs+Fj8An9m4n9qkj+dtMOaSTGCyOjzKZGB9P3QfXG5K3yVz6WcfzbyH7Xu0gokThbkFP+o5ex721+sG+Q0hbg44K5Hkw20LnC0kgXTDH/iZwska4PHaYUy1+K3wZ0laWxtR9QhJiBSdNoe9jZQJQeQJ8YGkBfVIyaPqkw6sFjNkL0=,iv:ChqiGb13Oqm5wX5/zZAm3bgNrm0R1d/okqAUiYiRCpc=,tag:r08WZAgoYrBHLnoBj3RefQ==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICnQDGTR3J244BlVZ3u0I9l476XRxlv0DdmREzTku3Ib abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGFJNmU1ZyBEbGJ6
            WjlTZ0RKSFM3bEV2TitZVGJabzk3d0VPcmU3MXYwWlNRdTdtOXk0Ck9BNDN4UW8r
            amRDUktvN09UdGdaZFg3RzlVcExxNEFhandGbnFkV25EVDQKLS0tIE03WjU4L2sx
            R0lhdE9jYkFnY3drZm9XNGVFb0FrTndZRHJTKzRuTnJPMmsKKT66x7itNbrJoS3l
            jvEKtAHEA24Wkzxpa9hedJyrdCKMd23tY8MmCOaSq+VKedGSLOzGkkOUTiwNP2iJ
            dSs83w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x43sjuly4kjrvmn07f8r77psgxa9f49d2egcmgl4aqkl7nmnafzqs56wzq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMXdRZ0k5TXVUNmFXa1dU
            Q3owSHZtdmFvSlVjVVhpcE5qRmdHbVd3cW4wCmM3d2ozeUp3THNjNlVRenhaemQw
            NUt4b1VheC92MnF3WWxRVWo3YTFMUUUKLS0tIGFQQUhUWFhueFdlV3BWVTBuSVU3
            R3U3cHUrUEpmRHFmREYvNmM5aEdxOGsK9X3QVhagtRCf0oES8P+n8LcrpFp9NxGN
            EylbEbLdCPD0Yxgp/iTGV3YuiXxNdPVPt6WJ07dMvpjbtnyAGZymuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPYkXD5kuITfXNUgU+yzirklzKXKRlT5ZKYwKo03lzzz abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGg2RGpKdyBiVE1K
            bTIwN0s5YnBrRUYvN2ZQMUpBaEZ4M2JTYXFKTlhuckVKc01HMENVCndMOHhEeVR2
            NjIzRndFSVdpOWJKWERuKzhsakl5NG1vSHFQSXpLS3BTMG8KLS0tIFkxWnNwWHpk
            Z05RazIzQnZCK0NqOVBHUnFpb0lLK21FZUtPYkw5K3JxMGsKZNidyRbfVwJWFlPa
            yECXQF+kdHl9MzyXlfPOhNsaXq4bR8v84gp66Zy36yg01kp/LtXnOBwahHAYJDLO
            JCYzVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII+cqj41D3k8Dk9Bz4l/06XVkkxMJIpg1orvuf56/Hme
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNSbC95dyBMNEpq
            SXM2TDh0ZXZsZnczS0grd1lVNTQwZ2NaRWtDdlFFOUt4ZktyRmlBClBqakxRT05m
            Zmttb1FXZ2NLZkdLai9PRXVpZ0xGREdVbkJsTG5TTEd5emcKLS0tICt3M1pvUlFF
            QURwL0gwUy9vNGJYR01EQ2VheHlEaDR1WXl1Y1VjOFlrcW8K8m4nD3UylQig2uBZ
            ctnBwx01xrzQHGw8YmtqOa1nVgADrKR6Q7zPl6e1zPAlOrQWeedRZlShWe9Ki7mr
            aVbM0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T02:09:48Z"
    mac: ENC[AES256_GCM,data:rc+Bkki5/5YKLvHmA9vQ2uCg3NarOA7VW0hzRhiI4sTZFZPDLJvq3Yjdu99Ks390YZ1ocRLUrAzGs8MRKp9f4yldWwphju8MPv+dOS9z97MPLLAwyO0Fu6l+GRWM1h3wqrDc4pRp5Q3jFu8T1FkbnFbBEBGyRLTFg4MZAWziQaM=,iv:d2jLWbEDNS5UWU+D4exr4zdQ3G6liPDxjZTPf6q5mlY=,tag:F9ghRMMn53LLmfE3RkMNrw==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
