apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:RFI8ZUP7etEt3YuaOuBkG5I0/An4fIO8tI9oTHhLGr5zbTCaITo8+mA63d4vPM4jqMWHr8pasQqC6rsohZzEROH3SmYgAiARwQKK3nm45pKdx/p2N5RQROw+sXl+g1RDDjrs6Z+Kp9+Q0oWNpqhPm/qmdSX/J0W1oQ27pzi0aJz13qekwePQWJoLNEwY7gHnL98CO8I8nHNihRSe66YI5ZBLemiz0KUcbXNTQAR1ouv93/kxUr+6rmL+yvhitvEE2B7QamMLgFl6wto/qS+m3SLQ7C3q4F1y5VY5zdtpyOXuoPH8JOn6QXWD6Mc=,iv:LvKBPuQ9Z39qITlBzJJ8JTKAgNkaACDnDsQr0IzbXjA=,tag:FDEs+y26/ejW6/0jxUKzAQ==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: blog
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICnQDGTR3J244BlVZ3u0I9l476XRxlv0DdmREzTku3Ib abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGFJNmU1ZyBQV0xy
            UEtybjFUaTdLbHpWU1JDVDkwWVhMYk5MRzJYdGtoNm1KbnZMbHp3ClNSaFZ2NzVU
            cnp6NndMemlUNDcwM3BNU3dhWWl2VTg2TlBudFZHb0QzRzQKLS0tIDNxQzBTRG1L
            bHY2aWZ0dUFXdGQ1RGNYYXFhN09lUDJsNDZJRmIxWGk2Qk0KnFmewBfoCCWI0ZiD
            GFsqur/20iAN25yGUKppWIQ9GAcjJon6qji/TJelArpvJIW61x1woCXmneYyEwuK
            LAKrtg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3aas35hvsswx2q04f2w7asg5373wvdydr4lufgdptjfq4hms9yq3au5rx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T1dVQzB6OFdIOG1vS3NB
            SE1xclpxQ3BKYVIrT09jdExIdFlraUs1T3k4CjQ1RnQ2K2Z1WFFSWlBmVkFEUExK
            bk96REd4MC96UituQlRZVTRjdGN3WDgKLS0tIEhpbnVyM3lsVFdtOXZuRWFsK2FM
            QzNReXR1Q3FyTjFZdG1EK3dpY0N2T2cKHPzNCInRUOMp5be1tKcKpsaFKazJU2ym
            FP98wk0/D9hJJvPzhW5C+XGwMtyGxXrq1y5SNx6R3/Yq48y+yRW73g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPYkXD5kuITfXNUgU+yzirklzKXKRlT5ZKYwKo03lzzz abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGg2RGpKdyB5Uk44
            RWhzbFpZZGxLSGtwTHVuL2QzTWlaM0FQRDFqaXc4NkRDT2FBRkNBCmNpTG9aRk94
            d2gvakw2UnZLSVNuUENrem1jK1pwb1R5UU1uZ3J5bGhXU2sKLS0tIEg5SGxyTENT
            a2hKZEhOd3ZpdC8vVGNXdmtOMjg4Ry90T3NuM2dVRGhXNEkKZIzVCR5WOSik5VKE
            sTC5lhhnqgZfnKFEUeX8yZAc6VRMzyqp5XarLg8tmrqRxk338xltVk0fEgxZcm2L
            eRRbuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII+cqj41D3k8Dk9Bz4l/06XVkkxMJIpg1orvuf56/Hme
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNSbC95dyA2bXA2
            R2E0V2FSL0g1R09WQVY2aUphSVRvRGlrdS9ubXpETDVCd1JzRmc0CnhmRjZKNldP
            TXZrdEpuRkxJOFBLSEhhTHJCWnlPUlVoQXMzKzd5c0NCRU0KLS0tIGRSV01adGNP
            Tm1kcmhpSlVLYkl2d1h6R2pMdXVkb0NsK0pBMGJ2QWNycUkK0gsz0b6IS7tKQCga
            rt1bMOBCd0kdVYfi7qnQg4RiWa7kwRsgbPCnFHY9rQ9xuZMq4L8HDTcs3WXHhWPh
            iwbRiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T23:02:11Z"
    mac: ENC[AES256_GCM,data:FGXsx25KrxhZxX17srujZC2+NFPS/CpgbIpIiWA6fXRqkzQxZCtczq8DWJk05vjsNPJfjVGN2FVK+L7w4H3rDok00qwll8LMjzP3qn9SIqP7eeKDJA2/3aL4FJehNTUtPJN5Z6Tog5GrNObTS0tCj3kXefNK2SEuzd+b4GcrsnM=,iv:F434atJguG8Y6wUG/UUrlxzj3FcIraaM6VTc8mCawIs=,tag:/HotIB0qxe+5IJSlqcZk9g==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.11.0
