apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:RFI8ZUP7etEt3YuaOuBkG5I0/An4fIO8tI9oTHhLGr5zbTCaITo8+mA63d4vPM4jqMWHr8pasQqC6rsohZzEROH3SmYgAiARwQKK3nm45pKdx/p2N5RQROw+sXl+g1RDDjrs6Z+Kp9+Q0oWNpqhPm/qmdSX/J0W1oQ27pzi0aJz13qekwePQWJoLNEwY7gHnL98CO8I8nHNihRSe66YI5ZBLemiz0KUcbXNTQAR1ouv93/kxUr+6rmL+yvhitvEE2B7QamMLgFl6wto/qS+m3SLQ7C3q4F1y5VY5zdtpyOXuoPH8JOn6QXWD6Mc=,iv:LvKBPuQ9Z39qITlBzJJ8JTKAgNkaACDnDsQr0IzbXjA=,tag:FDEs+y26/ejW6/0jxUKzAQ==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: blog
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICnQDGTR3J244BlVZ3u0I9l476XRxlv0DdmREzTku3Ib abutt@tiberius.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGFJNmU1ZyBScm1i
            YUNlVDBvSGUzcW03SGc1U01DNy91MExxV3lJU3VoZGVtc3EvK25ZCjhlcEhRZlZk
            OUhyVzRhU2FBVFI0SjVkWXNiKzVDWU5xbjdCeG1QaFhmcFUKLS0tIFRseW5WOHY0
            OUxPRkQycWprUi9XVDlPU3BmWDA2ZnAyNmlBeUFvb25kbEEK/qXRsi/DJOBA4sjY
            r6RDLJ9wRMV68Ro8w4fOaKaO4SDjCYN+5ke3Pei58H9mwi0QtMTs2g01THpPL4+8
            MqLkhg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r3aas35hvsswx2q04f2w7asg5373wvdydr4lufgdptjfq4hms9yq3au5rx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNDFUQVE0bVJzOUNpTGlY
            K3BLbyt5djVnYU9lczAxYmNHTVNwSWtybW5vCmgyM2NVY05JMFBYdEEwTFhzeWh6
            NnUvUEJLQTI0SWZlclE2ZDJZNWEvVnMKLS0tICs1MjVFUGFkcGpKOFFDM3FTY0ZU
            Q1RYTjE0SFplVjR2NnlaK21vS3cvK1UKarcjIb48XPYP2v84ir0LTLjyKTbpXSsb
            gIUEZu4kw6BkuXYXUR9WV99wuoYE1T7xJwTS4ziSIjvTnnlSr+hdgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T23:02:11Z"
    mac: ENC[AES256_GCM,data:FGXsx25KrxhZxX17srujZC2+NFPS/CpgbIpIiWA6fXRqkzQxZCtczq8DWJk05vjsNPJfjVGN2FVK+L7w4H3rDok00qwll8LMjzP3qn9SIqP7eeKDJA2/3aL4FJehNTUtPJN5Z6Tog5GrNObTS0tCj3kXefNK2SEuzd+b4GcrsnM=,iv:F434atJguG8Y6wUG/UUrlxzj3FcIraaM6VTc8mCawIs=,tag:/HotIB0qxe+5IJSlqcZk9g==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.11.0
