machine:
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.32.0
  install:
    image: ghcr.io/siderolabs/installer:v1.9.3
    extraKernelArgs:
      - net.ifnames=0
    disk: /dev/nvme0n1
cluster:
  apiServer:
    image: registry.k8s.io/kube-apiserver:v1.32.0
  controllerManager:
    image: registry.k8s.io/kube-controller-manager:v1.32.0
  scheduler:
    image: registry.k8s.io/kube-scheduler:v1.32.0
  network:
    cni:
      name: none
  proxy:
    disabled: true
  allowSchedulingOnControlPlanes: true
