metrics: 0.0.0.0:2000
no-autoupdate: true
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
ingress:
  - hostname: "sso.abutt.dev"
    service: https://kanidm.kanidm.svc.cluster.local:8443
    originRequest:
      noTLSVerify: true
  - hostname: "valentines.abutt.dev"
    service: http://valentines.valentines.svc.cluster.local:80
  - hostname: "blog.abutt.dev"
    service: http://blog.blog.svc.cluster.local:80
  - hostname: "*.abutt.dev"
    service: http://cilium-gateway-cloudflare-tunnel.default.svc.cluster.local:80
  - service: http_status:503
