apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
resources:
  - ../base
  - ns.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    reloader.stakater.com/auto: "true"
configMapGenerator:
  - name: cloudflared
    files:
      - config.yaml
secretGenerator:
  - name: tunnel-token
    envs:
      - secrets/token.encrypted.env
